/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolhub.presentacion;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.io.File;
import java.awt.Color;
import java.awt.Cursor;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.itson.SchoolHub.entidades.Curso;
import mx.itson.SchoolHub.enumeradores.TipoUsuario;
import mx.itson.SchoolHub.entidades.Usuario;
import mx.itson.SchoolHub.enumeradores.TiempoEngrega;
import static schoolhub.presentacion.SchoolHubCrearTarea.Descripcion1;
import static schoolhub.presentacion.SchoolHubCrearTarea.Descripcion2;
import static schoolhub.presentacion.SchoolHubCrearTarea.Descripcion3;
import static schoolhub.presentacion.SchoolHubCrearTarea.Descripcion4;
import static schoolhub.presentacion.SchoolHubCrearTarea.Fecha1;
import static schoolhub.presentacion.SchoolHubCrearTarea.Fecha2;
import static schoolhub.presentacion.SchoolHubCrearTarea.Fecha3;
import static schoolhub.presentacion.SchoolHubCrearTarea.Fecha4;
import static schoolhub.presentacion.SchoolHubCrearTarea.Tarea1;
import static schoolhub.presentacion.SchoolHubCrearTarea.Tarea2;
import static schoolhub.presentacion.SchoolHubCrearTarea.Tarea3;
import static schoolhub.presentacion.SchoolHubCrearTarea.Tarea4;
import static schoolhub.presentacion.SchoolHubPresentacion.SHPR;
import static schoolhub.presentacion.SchoolHubPresentacion.SHRV;
import static schoolhub.presentacion.SchoolHubPresentacion.SHT;
import static schoolhub.presentacion.SchoolHubRegistro.curso;
import static schoolhub.presentacion.SchoolHubTarea.lblHora;
import static schoolhub.presentacion.SchoolHubTarea.lblNombreTarea;
import static schoolhub.presentacion.SchoolHubTarea.txaDescripcion;

/**
 *
 * @author Cristian
 */
public class SchoolHubPrincipal extends javax.swing.JFrame {

    int yMouse;
    int xMouse;

    boolean panel1 = true;
    boolean panel2 = false;
    static boolean tarea1 = false;
    static boolean tarea2 = false;
    static boolean tarea3 = false;
    static boolean tarea4 = false;
    public static boolean isdocente;
    static DefaultTableModel model;
    static int usuarioNo;

    public SchoolHubPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTareas = new javax.swing.JTable();
        lblTarea = new javax.swing.JLabel();
        lblCrearAsignacion = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lbltipoUsuario = new javax.swing.JLabel();
        pnlTareas = new javax.swing.JPanel();
        lblTarea1 = new javax.swing.JLabel();
        lblFecha1 = new javax.swing.JLabel();
        lblTarea2 = new javax.swing.JLabel();
        lblFecha2 = new javax.swing.JLabel();
        lblTarea3 = new javax.swing.JLabel();
        lblFecha3 = new javax.swing.JLabel();
        lblTarea4 = new javax.swing.JLabel();
        lblFecha4 = new javax.swing.JLabel();
        lblFondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(914, 444));
        setUndecorated(true);
        getContentPane().setLayout(null);

        btnVer.setText("Ver");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer);
        btnVer.setBounds(410, 400, 73, 23);

        tblTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Asignacion", "Fecha limite"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTareas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblTareasComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(tblTareas);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(260, 160, 390, 220);

        lblTarea.setFont(new java.awt.Font("Earth Orbiter", 0, 24)); // NOI18N
        lblTarea.setForeground(new java.awt.Color(255, 255, 255));
        lblTarea.setText("Tareas");
        lblTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTareaMouseClicked(evt);
            }
        });
        getContentPane().add(lblTarea);
        lblTarea.setBounds(400, 130, 110, 30);

        lblCrearAsignacion.setFont(new java.awt.Font("Earth Orbiter", 0, 18)); // NOI18N
        lblCrearAsignacion.setForeground(new java.awt.Color(255, 255, 255));
        lblCrearAsignacion.setText("CRear Asignacion");
        lblCrearAsignacion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCrearAsignacionMouseMoved(evt);
            }
        });
        lblCrearAsignacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrearAsignacionMouseClicked(evt);
            }
        });
        getContentPane().add(lblCrearAsignacion);
        lblCrearAsignacion.setBounds(720, 40, 190, 25);

        lblCerrarSesion.setFont(new java.awt.Font("Earth Orbiter", 0, 18)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrarSesion.setText("Cerrar Sesión");
        lblCerrarSesion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseMoved(evt);
            }
        });
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
        });
        getContentPane().add(lblCerrarSesion);
        lblCerrarSesion.setBounds(750, 10, 150, 20);

        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/SchoolHub/imagenes/user (6).png"))); // NOI18N
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(410, 10, 64, 64);

        lblNombreUsuario.setFont(new java.awt.Font("Earth Orbiter", 0, 24)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setText("nombre USUARIO");
        lblNombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNombreUsuarioMouseClicked(evt);
            }
        });
        getContentPane().add(lblNombreUsuario);
        lblNombreUsuario.setBounds(320, 80, 240, 20);

        lbltipoUsuario.setForeground(new java.awt.Color(255, 0, 0));
        lbltipoUsuario.setText("Tipo de usuario");
        getContentPane().add(lbltipoUsuario);
        lbltipoUsuario.setBounds(30, 20, 80, 14);

        pnlTareas.setBackground(new java.awt.Color(34, 35, 38));
        pnlTareas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTarea1.setFont(new java.awt.Font("Terminator Two", 0, 18)); // NOI18N
        lblTarea1.setForeground(new java.awt.Color(255, 255, 255));
        lblTarea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTarea1MouseClicked(evt);
            }
        });

        lblFecha1.setFont(new java.awt.Font("Terminator Two", 0, 11)); // NOI18N
        lblFecha1.setForeground(new java.awt.Color(240, 240, 240));

        lblTarea2.setFont(new java.awt.Font("Terminator Two", 0, 18)); // NOI18N
        lblTarea2.setForeground(new java.awt.Color(255, 255, 255));
        lblTarea2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTarea2MouseClicked(evt);
            }
        });

        lblFecha2.setFont(new java.awt.Font("Terminator Two", 0, 11)); // NOI18N
        lblFecha2.setForeground(new java.awt.Color(240, 240, 240));

        lblTarea3.setFont(new java.awt.Font("Terminator Two", 0, 18)); // NOI18N
        lblTarea3.setForeground(new java.awt.Color(255, 255, 255));
        lblTarea3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTarea3MouseClicked(evt);
            }
        });

        lblFecha3.setFont(new java.awt.Font("Terminator Two", 0, 11)); // NOI18N
        lblFecha3.setForeground(new java.awt.Color(240, 240, 240));

        lblTarea4.setFont(new java.awt.Font("Terminator Two", 0, 18)); // NOI18N
        lblTarea4.setForeground(new java.awt.Color(255, 255, 255));
        lblTarea4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTarea4MouseClicked(evt);
            }
        });

        lblFecha4.setFont(new java.awt.Font("Terminator Two", 0, 11)); // NOI18N
        lblFecha4.setForeground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout pnlTareasLayout = new javax.swing.GroupLayout(pnlTareas);
        pnlTareas.setLayout(pnlTareasLayout);
        pnlTareasLayout.setHorizontalGroup(
            pnlTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTareasLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnlTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFecha3)
                    .addGroup(pnlTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFecha1)
                            .addComponent(lblTarea1))
                        .addGroup(pnlTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFecha2)
                            .addComponent(lblTarea2))
                        .addGroup(pnlTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFecha4)
                            .addComponent(lblTarea4))
                        .addComponent(lblTarea3)))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        pnlTareasLayout.setVerticalGroup(
            pnlTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTareasLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTarea1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTarea2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTarea3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFecha3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTarea4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTareas);
        pnlTareas.setBounds(340, 400, 350, 20);

        lblFondo2.setBackground(new java.awt.Color(34, 35, 38));
        lblFondo2.setOpaque(true);
        lblFondo2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblFondo2MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFondo2MouseMoved(evt);
            }
        });
        lblFondo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFondo2MousePressed(evt);
            }
        });
        getContentPane().add(lblFondo2);
        lblFondo2.setBounds(0, 0, 920, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
//        SchoolHubPresentacion SHP = new SchoolHubPresentacion();
        SHPR.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void lblTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTareaMouseClicked
        Usuario usuario = new Usuario();
        if (usuario.getTipoUsuario() == TipoUsuario.ALUMNO) {
            SchoolHubTarea SHT = new SchoolHubTarea();
            SHT.setVisible(true);
        }
        if (usuario.getTipoUsuario() == TipoUsuario.DOCENTE) {

        }
    }//GEN-LAST:event_lblTareaMouseClicked

    private void lblNombreUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNombreUsuarioMouseClicked
//lblTarea1.setText("Hola que hace we xddddddddddd");
    }//GEN-LAST:event_lblNombreUsuarioMouseClicked

    private void lblTarea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTarea1MouseClicked
        tarea1 = true;
        tarea2 = false;
        tarea3 = false;
        tarea4 = false;
        lblNombreTarea.setText(Tarea1);
        txaDescripcion.setText(Descripcion1);
        lblHora.setText(Fecha1);
        SHT.setVisible(true);
    }//GEN-LAST:event_lblTarea1MouseClicked

    private void lblTarea2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTarea2MouseClicked
        lblNombreTarea.setText(Tarea2);
        tarea1 = false;
        tarea2 = true;
        tarea3 = false;
        tarea4 = false;
        txaDescripcion.setText(Descripcion2);
        lblHora.setText(Fecha2);
        SHT.setVisible(true);
    }//GEN-LAST:event_lblTarea2MouseClicked

    private void lblTarea3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTarea3MouseClicked
        lblNombreTarea.setText(Tarea3);
        tarea1 = false;
        tarea2 = false;
        tarea3 = true;
        tarea4 = false;
        txaDescripcion.setText(Descripcion3);
        lblHora.setText(Fecha3);
        SHT.setVisible(true);
    }//GEN-LAST:event_lblTarea3MouseClicked

    private void lblTarea4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTarea4MouseClicked
        lblNombreTarea.setText(Tarea4);
        tarea1 = false;
        tarea2 = false;
        tarea3 = false;
        tarea4 = true;
        txaDescripcion.setText(Descripcion4);
        lblHora.setText(Fecha4);
        SHT.setVisible(true);
    }//GEN-LAST:event_lblTarea4MouseClicked

    private void lblCrearAsignacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearAsignacionMouseClicked
        SchoolHubCrearTarea SHCT = new SchoolHubCrearTarea();
        SHCT.setVisible(true);
    }//GEN-LAST:event_lblCrearAsignacionMouseClicked

    private void lblFondo2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondo2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();


    }//GEN-LAST:event_lblFondo2MousePressed

    private void lblFondo2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondo2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_lblFondo2MouseDragged

    private void lblFondo2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondo2MouseMoved
        lblCrearAsignacion.setForeground(Color.WHITE);
        lblCerrarSesion.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblFondo2MouseMoved

    private void lblCrearAsignacionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearAsignacionMouseMoved
        lblCrearAsignacion.setCursor(new Cursor(Cursor.HAND_CURSOR));

        lblCrearAsignacion.setForeground(Color.BLUE);
        lblCerrarSesion.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblCrearAsignacionMouseMoved

    private void lblCerrarSesionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseMoved
        lblCerrarSesion.setCursor(new Cursor(Cursor.HAND_CURSOR));

        lblCerrarSesion.setForeground(Color.BLUE);
        lblCrearAsignacion.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblCerrarSesionMouseMoved

    private void tblTareasComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblTareasComponentShown

    }//GEN-LAST:event_tblTareasComponentShown

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
//        Usuario usuario = new Usuario();
        if (tblTareas.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Favor de seleccionar un elemento", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        if (tblTareas.getSelectedRow() >= 0) {
            model = (DefaultTableModel) SchoolHubRevisar.tblAsignacion.getModel();
            model.setRowCount(0);

            if (isdocente == true) {
                try {
                    SchoolHubRevisar.nombreActividad.setText(tblTareas.getValueAt(tblTareas.getSelectedRow(), 0) + "");
                    File archivo = new File("Usuarios.txt");
                    Gson gson = new GsonBuilder().setPrettyPrinting().create();
                    if (archivo.exists()) {
                        BufferedReader rb = new BufferedReader(new FileReader("Usuarios.txt"));
                        curso = gson.fromJson(rb, Curso.class);
                        for (int var = 0; var < curso.getUsuario().size(); var++) {
                            if (curso.getUsuario().get(var).getTipoUsuario().toString().equals("ALUMNO")) {
                                for (int actividadID = 0; actividadID < curso.getUsuario().get(var).getAsignacionUsu().size(); actividadID++) {
                                    if (curso.getAsignacion().get(tblTareas.getSelectedRow()).getNombre().equals(curso.getUsuario().get(var).getAsignacionUsu().get(actividadID).getNombre())) {
                                        model.addRow(new Object[]{"" + curso.getUsuario().get(var).getNombre(), "" + curso.getUsuario().get(var).getAsignacionUsu().get(actividadID).getEngrega().toString()});
                                    }

                                }
                            }

                        }

                    }
                    SchoolHubRevisar.tblAsignacion.setModel(model);

                    SHRV.setVisible(true);
                } catch (IOException ex) {
                }
            }

            if (isdocente == false) {
                Date fechaActual = new Date();
                  SchoolHubTarea.lblNombreTarea.setText("" + curso.getUsuario().get(usuarioNo).getAsignacionUsu().get(tblTareas.getSelectedRow()).getNombre());
                SchoolHubTarea.txaDescripcion.setText(curso.getUsuario().get(usuarioNo).getAsignacionUsu().get(tblTareas.getSelectedRow()).getComentario());
                SchoolHubTarea.lblHora.setText("" + curso.getUsuario().get(usuarioNo).getAsignacionUsu().get(tblTareas.getSelectedRow()).getFechafinal());

                SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yyyy");
                String fecha = formateador.format(curso.getUsuario().get(SchoolHubPrincipal.usuarioNo).getAsignacionUsu().get(SchoolHubPrincipal.tblTareas.getSelectedRow()).getFechafinal());
                String fechaSistema = formateador.format(fechaActual);
                if (curso.getUsuario().get(SchoolHubPrincipal.usuarioNo).getAsignacionUsu().get(SchoolHubPrincipal.tblTareas.getSelectedRow()).isClose() == true) {
                    if (fechaSistema.compareTo(fecha) >= 1) {
                        JOptionPane.showMessageDialog(null, "Actividad bloqueada", "Fecha expirada", JOptionPane.INFORMATION_MESSAGE);

                    }

                    if (fechaSistema.compareTo(fecha) <= 0) {
                        SHT.setVisible(true);
                    }
                }
                if (curso.getUsuario().get(SchoolHubPrincipal.usuarioNo).getAsignacionUsu().get(SchoolHubPrincipal.tblTareas.getSelectedRow()).isClose() == false) {
                
                    SHT.setVisible(true);
                }

              
            }
        }


    }//GEN-LAST:event_btnVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void ActualizarLista() {
        try {
            model = (DefaultTableModel) tblTareas.getModel();
            model.setRowCount(0);
            Gson gson = new GsonBuilder().setPrettyPrinting().create();
            BufferedReader rb = new BufferedReader(new FileReader("Usuarios.txt"));
            curso = gson.fromJson(rb, Curso.class);
            if (isdocente == true) {
                for (int var = 0; var < curso.getAsignacion().size(); var++) {
                    model.addRow(new Object[]{"" + curso.getAsignacion().get(var).getNombre(), "" + curso.getAsignacion().get(var).getFechafinal(),});
                }

            } else {
                for (int var = 0; var < curso.getUsuario().get(usuarioNo).getAsignacionUsu().size(); var++) {
                    model.addRow(new Object[]{"" + curso.getUsuario().get(usuarioNo).getAsignacionUsu().get(var).getNombre(), "" + curso.getUsuario().get(usuarioNo).getAsignacionUsu().get(var).getFechafinal(),});
                }

            }
            tblTareas.setModel(model);

        } catch (Exception e) {
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolHubPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolHubPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolHubPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolHubPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchoolHubPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVer;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCerrarSesion;
    public static javax.swing.JLabel lblCrearAsignacion;
    public static javax.swing.JLabel lblFecha1;
    public static javax.swing.JLabel lblFecha2;
    public static javax.swing.JLabel lblFecha3;
    public static javax.swing.JLabel lblFecha4;
    public static javax.swing.JLabel lblFondo2;
    public static javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblTarea;
    public static javax.swing.JLabel lblTarea1;
    public static javax.swing.JLabel lblTarea2;
    public static javax.swing.JLabel lblTarea3;
    public static javax.swing.JLabel lblTarea4;
    private javax.swing.JLabel lblUsuario;
    public static javax.swing.JLabel lbltipoUsuario;
    public static javax.swing.JPanel pnlTareas;
    public static javax.swing.JTable tblTareas;
    // End of variables declaration//GEN-END:variables
}
