/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolhub.presentacion;

import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author Cristian
 */
public class SchoolHubRevisar extends javax.swing.JFrame {

     int yMouse;
    int xMouse;
    /**
     * Creates new form SchoolHubRevisar
     */
    public SchoolHubRevisar() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblAsignacion = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbCalificacion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblCalificacion = new javax.swing.JLabel();
        lblArchivoAdjunti = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        lblRevisar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(869, 459));
        setMinimumSize(new java.awt.Dimension(869, 459));
        setUndecorated(true);
        getContentPane().setLayout(null);

        tblAsignacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre de Alumno", "Estado de entrega"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAsignacion);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(520, 70, 330, 290);

        jLabel2.setFont(new java.awt.Font("Earth Orbiter", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Alumno");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 20, 170, 19);

        jLabel1.setFont(new java.awt.Font("Earth Orbiter", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AQUI VA EL NOMBRE DE LA ASIGNACION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 60, 400, 19);

        getContentPane().add(cmbCalificacion);
        cmbCalificacion.setBounds(340, 320, 60, 20);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 90, 380, 170);

        lblCalificacion.setFont(new java.awt.Font("Earth Orbiter", 0, 18)); // NOI18N
        lblCalificacion.setForeground(new java.awt.Color(255, 255, 255));
        lblCalificacion.setText("CALIFICACION");
        getContentPane().add(lblCalificacion);
        lblCalificacion.setBounds(170, 320, 160, 19);

        lblArchivoAdjunti.setFont(new java.awt.Font("Earth Orbiter", 0, 18)); // NOI18N
        lblArchivoAdjunti.setForeground(new java.awt.Color(255, 255, 255));
        lblArchivoAdjunti.setText("ABRIR ARCHIVO ADJUNTO");
        lblArchivoAdjunti.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblArchivoAdjuntiMouseMoved(evt);
            }
        });
        getContentPane().add(lblArchivoAdjunti);
        lblArchivoAdjunti.setBounds(170, 280, 260, 19);

        btnAceptar.setText("Aceptar");
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(230, 370, 71, 23);

        lblRevisar.setText("Revisar");
        getContentPane().add(lblRevisar);
        lblRevisar.setBounds(650, 30, 73, 23);

        lblFondo.setBackground(new java.awt.Color(34, 35, 38));
        lblFondo.setOpaque(true);
        lblFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblFondoMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFondoMouseMoved(evt);
            }
        });
        lblFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFondoMousePressed(evt);
            }
        });
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 870, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoMousePressed
xMouse = evt.getX();
    yMouse = evt.getY(); 
    }//GEN-LAST:event_lblFondoMousePressed

    private void lblFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoMouseDragged
       int x = evt.getXOnScreen();
    int y = evt.getYOnScreen(); 
    this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_lblFondoMouseDragged

    private void lblArchivoAdjuntiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArchivoAdjuntiMouseMoved
        lblArchivoAdjunti.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        lblArchivoAdjunti.setForeground(Color.BLUE);
    }//GEN-LAST:event_lblArchivoAdjuntiMouseMoved

    private void lblFondoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoMouseMoved
        lblArchivoAdjunti.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblFondoMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolHubRevisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolHubRevisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolHubRevisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolHubRevisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchoolHubRevisar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    public static javax.swing.JComboBox<String> cmbCalificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblArchivoAdjunti;
    private javax.swing.JLabel lblCalificacion;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JButton lblRevisar;
    private javax.swing.JTable tblAsignacion;
    // End of variables declaration//GEN-END:variables
}
