/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolhub.presentacion;

/**
 *
 * @author Cristian
 */
public class SchoolHubTarea extends javax.swing.JFrame {

    /**
     * Creates new form SchoolHubTarea
     */
    public SchoolHubTarea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scpRespuesta = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        scpDescripcion = new javax.swing.JScrollPane();
        txaDescripcion = new javax.swing.JTextArea();
        lblNombreTarea = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(595, 378));
        setMinimumSize(new java.awt.Dimension(595, 378));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        scpRespuesta.setViewportView(jTextArea2);

        getContentPane().add(scpRespuesta);
        scpRespuesta.setBounds(30, 240, 420, 110);

        txaDescripcion.setBackground(new java.awt.Color(0, 102, 102));
        txaDescripcion.setColumns(20);
        txaDescripcion.setFont(new java.awt.Font("Earth Orbiter", 0, 14)); // NOI18N
        txaDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txaDescripcion.setRows(5);
        txaDescripcion.setText("\nLorem ipsum dolor sit amet, consectetur adipiscing elit\n. Donec et pulvinar lectus. Quisque accumsan libero massa,\n sit amet pellentesque risus consectetur ac. \nQuisque eget turpis augue. Proin nec metus feugiat, \nporta sapien quis, pretium turpis. Maecenas sed eros ai\npsum pulvinar volutpat. Quisque mauris est,\n pretium sed molestie vel, congue.\n");
        scpDescripcion.setViewportView(txaDescripcion);

        getContentPane().add(scpDescripcion);
        scpDescripcion.setBounds(30, 70, 540, 150);

        lblNombreTarea.setFont(new java.awt.Font("Earth Orbiter", 2, 18)); // NOI18N
        lblNombreTarea.setText("Lorem Ipsum");
        getContentPane().add(lblNombreTarea);
        lblNombreTarea.setBounds(40, 30, 310, 30);

        lblHora.setFont(new java.awt.Font("Earth Orbiter", 2, 18)); // NOI18N
        lblHora.setText("99/99/9999");
        getContentPane().add(lblHora);
        lblHora.setBounds(420, 40, 130, 19);

        btnAgregar.setText("Adjuntar Archivo");
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(460, 250, 120, 23);

        btnEnviar.setText("Enviar");
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(460, 300, 120, 23);

        lblFondo.setBackground(new java.awt.Color(0, 204, 0));
        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 600, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolHubTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolHubTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolHubTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolHubTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchoolHubTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNombreTarea;
    private javax.swing.JScrollPane scpDescripcion;
    private javax.swing.JScrollPane scpRespuesta;
    private javax.swing.JTextArea txaDescripcion;
    // End of variables declaration//GEN-END:variables
}
