/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolhub.presentacion;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Date;
import javax.swing.JOptionPane;
import mx.itson.SchoolHub.entidades.Asignacion;
import mx.itson.SchoolHub.entidades.Curso;
import mx.itson.SchoolHub.entidades.Usuario;
import mx.itson.SchoolHub.enumeradores.TiempoEngrega;
import mx.itson.SchoolHub.enumeradores.TipoAsignacion;
import mx.itson.SchoolHub.enumeradores.TipoUsuario;
import static schoolhub.presentacion.SchoolHubPrincipal.lblFecha1;
import static schoolhub.presentacion.SchoolHubPrincipal.lblFecha2;
import static schoolhub.presentacion.SchoolHubPrincipal.lblFecha3;
import static schoolhub.presentacion.SchoolHubPrincipal.lblFecha4;
import static schoolhub.presentacion.SchoolHubPrincipal.lblTarea1;
import static schoolhub.presentacion.SchoolHubPrincipal.lblTarea2;
import static schoolhub.presentacion.SchoolHubPrincipal.lblTarea3;
import static schoolhub.presentacion.SchoolHubPrincipal.lblTarea4;
import static schoolhub.presentacion.SchoolHubRegistro.curso;
import static schoolhub.presentacion.SchoolHubTarea.lblHora;
import static schoolhub.presentacion.SchoolHubTarea.lblNombreTarea;
import static schoolhub.presentacion.SchoolHubTarea.txaDescripcion;

/**
 *
 * @author Cristian
 */
public class SchoolHubCrearTarea extends javax.swing.JFrame {
 public static String Tarea1;
 public static String Tarea2;
 public static String Tarea3;
 public static String Tarea4;
 public static String Descripcion1;
 public static String Descripcion2;
 public static String Descripcion3;
 public static String Descripcion4;
 public static String Fecha1;
 public static String Fecha2;
 public static String Fecha3;
 public static String Fecha4;
 int yMouse;
 int xMouse;
    /**
     * Creates new form SchoolHubCrearTarea
     */
    public SchoolHubCrearTarea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        txtnombreAsig = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblNombreTarea2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescripcion2 = new javax.swing.JTextArea();
        cmbTipo = new javax.swing.JComboBox<>();
        cmbDia = new javax.swing.JComboBox<>();
        cmdMes = new javax.swing.JComboBox<>();
        cmbAño = new javax.swing.JComboBox<>();
        lblEntrega = new javax.swing.JLabel();
        rbsi = new javax.swing.JRadioButton();
        rbno = new javax.swing.JRadioButton();
        btnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblHora2 = new javax.swing.JLabel();
        rbnEntregoNoEntrego = new javax.swing.JRadioButton();
        rbnEscala = new javax.swing.JRadioButton();
        lblMaximo = new javax.swing.JTextField();
        lblCalificacion = new javax.swing.JLabel();
        lblHoraLimite = new javax.swing.JLabel();
        cmbHora = new javax.swing.JComboBox<>();
        cmbMinuto = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(415, 539));
        setMinimumSize(new java.awt.Dimension(415, 539));
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(txtnombreAsig);
        txtnombreAsig.setBounds(220, 30, 170, 30);

        lblTipo.setFont(new java.awt.Font("Earth Orbiter", 0, 14)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo.setText("TIPO DE ASIGNACION :");
        getContentPane().add(lblTipo);
        lblTipo.setBounds(30, 70, 180, 15);

        lblDescripcion.setFont(new java.awt.Font("Earth Orbiter", 0, 14)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setText("Descripción :");
        getContentPane().add(lblDescripcion);
        lblDescripcion.setBounds(30, 310, 120, 15);

        lblNombreTarea2.setFont(new java.awt.Font("Earth Orbiter", 0, 14)); // NOI18N
        lblNombreTarea2.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreTarea2.setText("Nombre de Asignación :");
        getContentPane().add(lblNombreTarea2);
        lblNombreTarea2.setBounds(30, 30, 190, 20);

        txaDescripcion2.setColumns(20);
        txaDescripcion2.setRows(5);
        jScrollPane1.setViewportView(txaDescripcion2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 330, 370, 150);

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASIGNACION", "TAREA", "ACTIVIDAD" }));
        getContentPane().add(cmbTipo);
        cmbTipo.setBounds(220, 70, 120, 20);

        cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cmbDia);
        cmbDia.setBounds(140, 110, 50, 20);

        cmdMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        getContentPane().add(cmdMes);
        cmdMes.setBounds(210, 110, 70, 20);

        cmbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018" }));
        getContentPane().add(cmbAño);
        cmbAño.setBounds(300, 110, 80, 20);

        lblEntrega.setFont(new java.awt.Font("Earth Orbiter", 0, 14)); // NOI18N
        lblEntrega.setForeground(new java.awt.Color(255, 255, 255));
        lblEntrega.setText("Entrega después de fecha limite :");
        getContentPane().add(lblEntrega);
        lblEntrega.setBounds(30, 190, 280, 15);

        buttonGroup1.add(rbsi);
        rbsi.setFont(new java.awt.Font("Earth Orbiter", 0, 14)); // NOI18N
        rbsi.setForeground(new java.awt.Color(255, 255, 255));
        rbsi.setSelected(true);
        rbsi.setText("Si");
        rbsi.setOpaque(false);
        getContentPane().add(rbsi);
        rbsi.setBounds(310, 190, 40, 20);

        buttonGroup1.add(rbno);
        rbno.setFont(new java.awt.Font("Earth Orbiter", 0, 14)); // NOI18N
        rbno.setForeground(new java.awt.Color(255, 255, 255));
        rbno.setText("No");
        rbno.setOpaque(false);
        getContentPane().add(rbno);
        rbno.setBounds(350, 190, 50, 20);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(180, 490, 71, 23);

        jLabel1.setBackground(new java.awt.Color(34, 35, 38));
        jLabel1.setFont(new java.awt.Font("Earth Orbiter", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TIPO DE CALIFICACION :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 220, 200, 15);

        lblHora2.setFont(new java.awt.Font("Earth Orbiter", 0, 14)); // NOI18N
        lblHora2.setForeground(new java.awt.Color(255, 255, 255));
        lblHora2.setText("Fecha Limite:");
        getContentPane().add(lblHora2);
        lblHora2.setBounds(30, 110, 120, 15);

        buttonGroup2.add(rbnEntregoNoEntrego);
        rbnEntregoNoEntrego.setFont(new java.awt.Font("Earth Orbiter", 0, 14)); // NOI18N
        rbnEntregoNoEntrego.setForeground(new java.awt.Color(255, 255, 255));
        rbnEntregoNoEntrego.setText("Entrego/No Entrego");
        rbnEntregoNoEntrego.setOpaque(false);
        getContentPane().add(rbnEntregoNoEntrego);
        rbnEntregoNoEntrego.setBounds(30, 250, 200, 23);

        buttonGroup2.add(rbnEscala);
        rbnEscala.setFont(new java.awt.Font("Earth Orbiter", 0, 14)); // NOI18N
        rbnEscala.setForeground(new java.awt.Color(255, 255, 255));
        rbnEscala.setText("Escala");
        rbnEscala.setOpaque(false);
        getContentPane().add(rbnEscala);
        rbnEscala.setBounds(290, 250, 90, 23);
        getContentPane().add(lblMaximo);
        lblMaximo.setBounds(250, 280, 50, 20);

        lblCalificacion.setFont(new java.awt.Font("Earth Orbiter", 0, 14)); // NOI18N
        lblCalificacion.setForeground(new java.awt.Color(255, 255, 255));
        lblCalificacion.setText("Maxima :");
        getContentPane().add(lblCalificacion);
        lblCalificacion.setBounds(180, 280, 70, 15);

        lblHoraLimite.setFont(new java.awt.Font("Earth Orbiter", 0, 14)); // NOI18N
        lblHoraLimite.setForeground(new java.awt.Color(255, 255, 255));
        lblHoraLimite.setText("HORA LIMITE :");
        getContentPane().add(lblHoraLimite);
        lblHoraLimite.setBounds(30, 150, 120, 20);

        cmbHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11" }));
        getContentPane().add(cmbHora);
        cmbHora.setBounds(150, 150, 50, 20);

        cmbMinuto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "56", "57", "58", "59" }));
        getContentPane().add(cmbMinuto);
        cmbMinuto.setBounds(210, 150, 50, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(270, 150, 50, 20);

        lblFondo.setBackground(new java.awt.Color(34, 35, 38));
        lblFondo.setOpaque(true);
        lblFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblFondoMouseDragged(evt);
            }
        });
        lblFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFondoMousePressed(evt);
            }
        });
        getContentPane().add(lblFondo);
        lblFondo.setBounds(-4, -5, 420, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        
        if (lblTarea1.getText().isEmpty()) {
            lblTarea1.setText(txtnombreAsig.getText());
            Tarea1 = txtnombreAsig.getText();
            Fecha1 = cmbDia.getSelectedItem().toString()+"/"+cmdMes.getSelectedItem().toString()+"/"+cmbAño.getSelectedItem().toString();
            Descripcion1 = txaDescripcion2.getText();
        lblFecha1.setText("Fecha de entrega: "+cmbDia.getSelectedItem().toString()+"/"+cmdMes.getSelectedItem().toString()+"/"+cmbAño.getSelectedItem().toString());
        }else if (lblTarea2.getText().isEmpty()) {
             Tarea2 = txtnombreAsig.getText();
            Fecha2 = cmbDia.getSelectedItem().toString()+"/"+cmdMes.getSelectedItem().toString()+"/"+cmbAño.getSelectedItem().toString();
            Descripcion2 = txaDescripcion2.getText();
            lblTarea2.setText(txtnombreAsig.getText());
        lblFecha2.setText("Fecha de entrega: "+cmbDia.getSelectedItem().toString()+"/"+cmdMes.getSelectedItem().toString()+"/"+cmbAño.getSelectedItem().toString());
        }else if (lblTarea3.getText().isEmpty()) {
             Tarea3 = txtnombreAsig.getText();
            Fecha3 = cmbDia.getSelectedItem().toString()+"/"+cmdMes.getSelectedItem().toString()+"/"+cmbAño.getSelectedItem().toString();
            Descripcion3 = txaDescripcion2.getText();
            lblTarea3.setText(txtnombreAsig.getText());
        lblFecha3.setText("Fecha de entrega: "+cmbDia.getSelectedItem().toString()+"/"+cmdMes.getSelectedItem().toString()+"/"+cmbAño.getSelectedItem().toString());
        }else if (lblTarea4.getText().isEmpty()) {
             Tarea4 = txtnombreAsig.getText();
            Fecha4 = cmbDia.getSelectedItem().toString()+"/"+cmdMes.getSelectedItem().toString()+"/"+cmbAño.getSelectedItem().toString();
            Descripcion4 = txaDescripcion2.getText();
            lblTarea4.setText(txtnombreAsig.getText());
        lblFecha4.setText("Fecha de entrega: "+cmbDia.getSelectedItem().toString()+"/"+cmdMes.getSelectedItem().toString()+"/"+cmbAño.getSelectedItem().toString());
        }
//        lblTarea1.setText(txtnombreAsig.getText());
//        lblFecha1.setText("Fecha de entrega: "+cmbDia.getSelectedItem().toString()+"/"+cmdMes.getSelectedItem().toString()+"/"+cmbAño.getSelectedItem().toString());
       // lblNombreTarea.setText(txtnombreAsig.getText());
       // txaDescripcion.setText(txaDescripcion2.getText());
       // lblHora.setText(cmbDia.getSelectedItem().toString()+"/"+cmdMes.getSelectedItem().toString()+"/"+cmbAño.getSelectedItem().toString());
        
        
        try {
             boolean bloqueo = false;
            SchoolHubPresentacion SHP = new SchoolHubPresentacion();
            boolean repe = false;
            File archivo = new File("Usuarios.txt");
            BufferedWriter bw;
            Gson gson = new GsonBuilder().setPrettyPrinting().create();

            if (archivo.exists()) {
               
                    
             

                    BufferedReader rb = new BufferedReader(new FileReader("Usuarios.txt"));
                    curso = gson.fromJson(rb, Curso.class);

                    
                        if(rbsi.isSelected()){
                            bloqueo= true;
                        }
                        curso.getAsignacion().add(new Asignacion(txtnombreAsig.getText(), TipoAsignacion.valueOf(cmbTipo.getSelectedItem().toString()), txaDescripcion2.getText(), new Date(), new Date(), 0, TiempoEngrega.NoEntregado, bloqueo));
//                        lblTarea1.setText(txtnombreAsig.getText());
//                        lblFecha1.setText("Fecha de entrega: "+cmbDia.getSelectedItem().toString()+"/"+cmdMes.getSelectedItem().toString()+"/"+cmbAño.getSelectedItem().toString());
                        
                        String textoUsuario = gson.toJson(curso);

                        bw = new BufferedWriter(new FileWriter(archivo));
                        bw.write("" + textoUsuario);

                        bw.close();
                        
                        this.setVisible(false);

                    
                    

               

            }
            else{
                curso = new Curso();
                //curso.getUsuario().add(new Usuario(txtNombre.getText(), TipoUsuario.valueOf(cmbCuenta.getSelectedItem().toString()), txtCorreo.getText(), "asd", 0));
                String textoUsuario = gson.toJson(curso);
                bw = new BufferedWriter(new FileWriter(archivo));
                        bw.write("" + textoUsuario);
// lblTarea1.setText(txtnombreAsig.getText());
//                        lblFecha1.setText("Fecha de entrega: "+cmbDia.getSelectedItem().toString()+"/"+cmdMes.getSelectedItem().toString()+"/"+cmbAño.getSelectedItem().toString());
                        bw.close();
                        SHP.setVisible(true);
                        this.setVisible(false);
            }
        } catch (IOException ex) {
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void lblFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoMousePressed
    xMouse = evt.getX();
    yMouse = evt.getY(); 
    }//GEN-LAST:event_lblFondoMousePressed

    private void lblFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoMouseDragged
    int x = evt.getXOnScreen();
    int y = evt.getYOnScreen(); 
    this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_lblFondoMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolHubCrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolHubCrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolHubCrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolHubCrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchoolHubCrearTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbAño;
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbHora;
    private javax.swing.JComboBox<String> cmbMinuto;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JComboBox<String> cmdMes;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCalificacion;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEntrega;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHora2;
    private javax.swing.JLabel lblHoraLimite;
    private javax.swing.JTextField lblMaximo;
    private javax.swing.JLabel lblNombreTarea2;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JRadioButton rbnEntregoNoEntrego;
    private javax.swing.JRadioButton rbnEscala;
    public static javax.swing.JRadioButton rbno;
    public static javax.swing.JRadioButton rbsi;
    public static javax.swing.JTextArea txaDescripcion2;
    public static javax.swing.JTextField txtnombreAsig;
    // End of variables declaration//GEN-END:variables
}
