/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolhub.presentacion;

import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static schoolhub.presentacion.SchoolHubPrincipal.tarea1;
import static schoolhub.presentacion.SchoolHubPrincipal.tarea2;
import static schoolhub.presentacion.SchoolHubPrincipal.tarea3;
import static schoolhub.presentacion.SchoolHubPrincipal.tarea4;


public class SchoolHubTarea extends javax.swing.JFrame {
JFileChooser seleccionar = new JFileChooser();
    File archivo;
    /**
     * Creates new form SchoolHubTarea
     */
    public SchoolHubTarea() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scpRespuesta = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        scpDescripcion = new javax.swing.JScrollPane();
        txaDescripcion = new javax.swing.JTextArea();
        lblNombreTarea = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(595, 378));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        scpRespuesta.setViewportView(jTextArea2);

        getContentPane().add(scpRespuesta);
        scpRespuesta.setBounds(30, 240, 420, 110);

        txaDescripcion.setEditable(false);
        txaDescripcion.setBackground(new java.awt.Color(0, 102, 102));
        txaDescripcion.setColumns(20);
        txaDescripcion.setFont(new java.awt.Font("Earth Orbiter", 0, 14)); // NOI18N
        txaDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txaDescripcion.setRows(5);
        txaDescripcion.setText("\nLorem ipsum dolor sit amet, consectetur adipiscing elit\n. Donec et pulvinar lectus. Quisque accumsan libero massa,\n sit amet pellentesque risus consectetur ac. \nQuisque eget turpis augue. Proin nec metus feugiat, \nporta sapien quis, pretium turpis. Maecenas sed eros ai\npsum pulvinar volutpat. Quisque mauris est,\n pretium sed molestie vel, congue.\n");
        scpDescripcion.setViewportView(txaDescripcion);

        getContentPane().add(scpDescripcion);
        scpDescripcion.setBounds(30, 70, 540, 150);

        lblNombreTarea.setFont(new java.awt.Font("Earth Orbiter", 2, 18)); // NOI18N
        lblNombreTarea.setText("Lorem Ipsum");
        getContentPane().add(lblNombreTarea);
        lblNombreTarea.setBounds(40, 30, 310, 30);

        lblHora.setFont(new java.awt.Font("Earth Orbiter", 2, 18)); // NOI18N
        lblHora.setText("99/99/9999");
        getContentPane().add(lblHora);
        lblHora.setBounds(420, 40, 130, 19);

        btnAgregar.setText("Adjuntar Archivo");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(460, 250, 120, 23);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(460, 300, 120, 23);

        lblFondo.setBackground(new java.awt.Color(0, 204, 0));
        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 600, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
         if (seleccionar.showDialog(null, "Abrir")== JFileChooser.APPROVE_OPTION){
            archivo=seleccionar.getSelectedFile();
          if(archivo.canRead()){
              if(archivo.getName().endsWith("txt")|| archivo.getName().endsWith("pdf")|| archivo.getName().endsWith("docx")){
                  Path origenPath = FileSystems.getDefault().getPath(archivo.getAbsolutePath());
        Path destinoPath = FileSystems.getDefault().getPath("C:\\Users\\josef\\Documents\\NetBeansProjects\\EjemploTXT\\xd\\"+ archivo.getName());
                 try {
            Files.move(origenPath, destinoPath, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException e) {
            System.err.println(e);
        }
              }else{
                  JOptionPane.showMessageDialog(null, "Archivo no compatible");
              }
          }  
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if(tarea1== true){
            SchoolHubPrincipal.lblTarea1.setVisible(false);
            
        }
        if(tarea2== true){
            SchoolHubPrincipal.lblTarea2.setVisible(false);
            
        }
        if(tarea3== true){
            SchoolHubPrincipal.lblTarea3.setVisible(false);
            
        }
        if(tarea4== true){
            SchoolHubPrincipal.lblTarea4.setVisible(false);
            
        }
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolHubTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolHubTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolHubTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolHubTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchoolHubTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblFondo;
    public static javax.swing.JLabel lblHora;
    public static javax.swing.JLabel lblNombreTarea;
    private javax.swing.JScrollPane scpDescripcion;
    private javax.swing.JScrollPane scpRespuesta;
    public static javax.swing.JTextArea txaDescripcion;
    // End of variables declaration//GEN-END:variables
}
